### ISSUE TITLE
Support for custom renderers

### ISSUE THREAD

**Issue by ajeetdsouza** [monosans/pyromark#400]
Hey, thanks for this library! It would be great if you could also provide a way for users to build custom Markdown renderers. This is supported by pure-Python libraries like Mistune / Mistletoe.

**Comment by monosans** [comment]
Will implement it this week

**Comment by monosans** [comment]
Implemented, but not released yet: <https://github.com/monosans/pyromark#iterating-over-markdown-elements>.

Let me know if I am missing something

**Comment by ajeetdsouza** [comment]
Thank you!
